# syntax=docker/dockerfile:1
FROM node:22.12.0-alpine

# Install OS packages needed for Electron + Git
RUN apk update && apk add --no-cache \
    libx11 \
    libxkbfile \
    udev \
    ttf-freefont \
    git \
    && rm -rf /var/cache/apk/*

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

RUN npm install

# Copy source files
COPY . .

CMD ["npx", "electron-forge", "start"]
